image: Visual Studio 2015

version: build-{build}-{branch}

before_build:
  - copy /y  tools\AppVeyor\Microsoft.DriverKit.Build.Tasks.14.0.dll "C:\Program Files (x86)\Windows Kits\10\build\bin"

build_script: buildAll.bat

skip_commits:
  message: /\[ci skip\]/

notifications:
  - provider: Email
    to: devel@daynix.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
