image: Visual Studio 2015

version: build-{build}-{branch}

before_build:
  - tools\AppVeyor\before-build.cmd

build_script: buildAll.bat

skip_commits:
  message: /\[ci skip\]/

notifications:
  - provider: Email
    to: devel@daynix.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
